### PR TITLE
Move all class renames to CSV files for easier scriptability

### PR DESCRIPTION
**Pull request by JoJoDeveloping**
As discussed in #mcpconfig

The script used to do this can be found here: https://gist.github.com/JoJoDeveloping/15fef58771bbebdc5ed26bfdeeffc35b

### CODE REVIEW

**Comment by williewillus** [comment]
can the format be unified? some of the csvs use dots while others use slashes, and some are fully qualified while others are not

**Comment by kashike** [comment]
Think you could make the class names fully-qualified (include `net.minecraft.` in them)?

**Comment by JoJoDeveloping** [comment]
@williewillus
Huh I didn't notice that. Will fix. I'd say vote up for . names and down for /..

@kashike I was told not to do this, but if wanted I still can.. It's more readable without and adding "net.minecraft." to everything is not that hard.

**Comment by kashike** [comment]
Please do add `net.minecraft.` - thanks!

**Comment by JoJoDeveloping** [comment]
did so

**Comment by williewillus** [comment]
there's some lines in there that look like this: `net.minecraft.world.biome.BiomeVoidDecorator,net.minecraft.*[removed]*`

which showed that the class was removed. These listings are incomplete and we should just delete those entries, the csv's should just be for renamings, not additions or removals.

**Pull request merged**
